# Generated by Django 6.0.5 on 2026-05-19 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='식물 별명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('vitality', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='활력도')),
                ('stress_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='스트레스 지수')),
                ('growth_stage', models.CharField(choices=[('SEED', '새싹'), ('GROWING', '성장기'), ('MATURE', '성체'), ('FLOWERING', '개화')], default='SEED', max_length=20, verbose_name='성장 단계')),
                ('garden_position_x', models.FloatField(default=0.0)),
                ('garden_position_y', models.FloatField(default=0.0)),
                ('garden_theme', models.CharField(default='indoor', max_length=50, verbose_name='정원 테마')),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='식물 이름')),
                ('scientific_name', models.CharField(blank=True, max_length=200, verbose_name='학명')),
                ('description', models.TextField(verbose_name='설명')),
                ('ideal_temp_min', models.FloatField(default=15.0, verbose_name='최저 적정 온도')),
                ('ideal_temp_max', models.FloatField(default=28.0, verbose_name='최고 적정 온도')),
                ('ideal_humidity_min', models.FloatField(default=40.0, verbose_name='최저 적정 습도')),
                ('ideal_humidity_max', models.FloatField(default=70.0, verbose_name='최고 적정 습도')),
                ('sunlight_requirement', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='빛 요구도')),
                ('default_watering_interval', models.IntegerField(default=7, verbose_name='기본 물주기 주기(일)')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=20, verbose_name='지역 코드')),
                ('temperature', models.FloatField(verbose_name='기온')),
                ('humidity', models.FloatField(verbose_name='습도')),
                ('uv_index', models.FloatField(blank=True, null=True, verbose_name='자외선 지수')),
                ('condition_text', models.CharField(max_length=100, verbose_name='날씨 상태')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시간')),
            ],
        ),
        migrations.CreateModel(
            name='CareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WATER', '물주기'), ('NUTRIENT', '영양제'), ('REPOT', '분갈이'), ('PRUNE', '가지치기')], max_length=20, verbose_name='수행 작업')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='수행 시간')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_records', to='plants.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='plants.plantspecies'),
        ),
        migrations.CreateModel(
            name='WateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='예정일')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('adjustment_reason', models.CharField(blank=True, max_length=255, verbose_name='일정 조정 사유')),
                ('original_date', models.DateField(blank=True, null=True, verbose_name='기초 예정일')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='plants.plant')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
    ]
