# Generated by Django 6.0.5 on 2026-05-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('INCHEON', '인천'), ('DAEGU', '대구'), ('DAEJEON', '대전'), ('GWANGJU', '광주'), ('ULSAN', '울산'), ('SEJONG', '세종'), ('GYEONGGI', '경기'), ('GANGWON', '강원'), ('CHUNGBUK', '충북'), ('CHUNGNAM', '충남'), ('JEONBUK', '전북'), ('JEONNAM', '전남'), ('GYEONGBUK', '경북'), ('GYEONGNAM', '경남'), ('JEJU', '제주')], default='SEOUL', max_length=20, verbose_name='재배 지역'),
        ),
    ]
