# Generated by Django 6.0.5 on 2026-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(default='강남구', max_length=100, verbose_name='재배 지역 (시/군/구)'),
        ),
    ]
