# Generated by Django 6.0.5 on 2026-05-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_user_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='theme',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_farm',
            field=models.BooleanField(default=False, verbose_name='활기찬 농장 테마 사용'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_garden',
            field=models.BooleanField(default=False, verbose_name='비밀의 정원 테마 사용'),
        ),
    ]
