# Generated by Django 6.0.5 on 2026-05-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_remove_userprofile_theme_userprofile_theme_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='emoji',
            field=models.CharField(default='🌿', max_length=10, verbose_name='식물 아이콘'),
        ),
    ]
